databases:
  - name: library_website_db
    plan: free
    databaseName: library_website
    user: library_website

services:
  - type: web
    plan: free
    name: library_website
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn library_website.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library_website_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4